# Generated by Django 5.1.4 on 2025-01-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_pedidos', '0002_remove_pedido_produto_cliente_endereco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='quantidade',
        ),
    ]
